### PR TITLE
NR: Kinesis Update

### PR DESCRIPTION
**Pull request by pzapletal**

### CODE REVIEW

**Comment by fommil** [comment]
if you're cutting a release make sure to add the tag to this repo, otherwise it's really easy to overwrite published images and that will cause chaos.

**Comment by pzapletal** [comment]
will keep it in mind. gonna create additional PR, as yourkit dep is broken anyway. Love how they removing old archives

**Comment by pzapletal** [comment]
btw. do you remember why we are using 3.4X version of NR?

**Comment by fommil** [comment]
that was the latest version when we made these... just upgrade to the latest.

Do we need to delete any of the old akka images or anything? Stale instrumentation is probably not a good thing if it's rolled into the latest releases.

**Comment by pzapletal** [comment]
https://github.com/cakesolutions/docker-images-public/pull/11

**Pull request merged**
